def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

setup_permissions([
  'Camera',
  'FaceID',
  'Notifications',
  'PhotoLibrary',
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

project 'DetoxReloadApp',
  'Debug' => :debug,
  'Release' => :release,
  'DiscoveraDebug' => :debug,
  'DiscoveraRelease' => :release

target 'DetoxReloadApp' do

  # CUSTOM CHANGE from @react-native-maps
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-maps/Google', :path => rn_maps_path

  config = use_native_modules!

  # CUSTOM CHANGE from @react-native-firebase/app@22
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  # CUSTOM CHANGE from @react-native-firebase/analytics
  $RNFirebaseAnalyticsWithoutAdIdSupport=true

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :cache_enabled => true
    )
  end
end
